name: Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout blog source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"

      - name: Build
        run: hugo --config=config.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          EXTERNAL_REPOSITORY: morak-morak/morak-morak.github.io
          ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
